Adding ENABLE_ZGC
AlexProgrammerDE/balena-minecraft-server pull request #175
Opened 2021-11-01 22:19 UTC by taedium8vitae

### Change-type: minor

Hey there ! I just added the variable `ENABLE_ZGC`, which if set to true will change the java startup flags to use [the Z Garbage Collector](https://wiki.openjdk.java.net/display/zgc/Main). I am asking to merge this change because it helped me reduce drastically RAM consumption on my server ! Like... DRASTICALLY !

2021-11-01 22:20 UTC, taedium8vitae commented on mc-server/start.sh
> -java -Xms$RAM -Xmx$RAM -jar $JAR_FILE
I just rewrote it below, don't worry I didn't delete the most important part of the file...

2021-11-07 07:14 UTC, AlexProgrammerDE requested changes
The idea is good, but if we want to also add things like aikar flags and gc logging stuff or another garbage cleaner, it can quickly get overcomplicated. My idea would be to add a simple variable that combines all startup flags, can add predefined flags if set by a variable and allows the user to add custom flags too via a variable in the balena dashboard. Will soon try to work out a system for this.

2021-11-07 11:25 UTC, taedium8vitae commented
The thing is, combining aikar's flags and the ZGC propably isn't a good idea. It really depends on what the user needs. Since this level of customisation will probably not be met by the majority of the users, I think two simple variables would be great. Example :
```
$ENABLE_FLAGS = true
$FLAGS = the user inserts his preferred flags here
```
The idea here is that the few people who want to go as far as customising the startup flags are probably willing to write them manually in a variable. This doesn't need to be "rookie friendly".
The only detail I haven't thought of is how we can implement the `$RAM` variable in this system, maybe make the Xms and Xmx stay even with the custom flags or just tell the user in the documentation how he can use it ?
Anyways, keep responding so we can figure the better way together !

2021-11-07 11:34 UTC, taedium8vitae commented
PS : I converted it to draft so we can work on the project here if you want.

2021-12-04 17:53 UTC, AlexProgrammerDE commented
Will make one last check and merge after that.

2021-12-04 18:27 UTC, AlexProgrammerDE approved these changes
LGTM! Thanks for your work!

2021-12-04 18:27 UTC, merged